name: alterra_chat
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_fonts: ^3.0.1
  responsive_framework: ^0.2.0
  firebase_core: ^2.1.1
  firebase_auth: ^4.1.1
  provider: ^6.0.4
  cloud_firestore: ^4.0.4
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_launcher_icons: "^0.10.0"

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

flutter_icons:
 android: true
 ios: true
 image_path: "assets/app_logo.png"